library(lubridate)
library(dplyr)
library(jsonlite)
library(ggplot2)
library(survival)
library(stringr)

source("/home/okhotin/Dropbox/R/masters/echo-data.R")

# /home/okhotin/Dropbox/R/masters

# Give the input file name to the function.
df <- fromJSON(txt = "/home/okhotin/Dropbox/R/masters/cardioversions.json")

df <- df %>% mutate(id = row_number()) ## add unique id

df <- df %>%              # exclude records, excluded in EHR
  filter(is.na(exclude))

df <- df %>%                # adding physicians based on the records and merging
  mutate(physician = ifelse(physician == 'Василий Максимович Осипов',
                            'Василий Осипов', physician)) %>%
  mutate(physician = ifelse(physician == 'Максим Александрович Осипов',
                            'Максим Осипов', physician)) %>%
  mutate(physician = ifelse(grepl("drmaximosipov", record) & physician == "none",
                            'Максим Осипов', physician)) %>%
  mutate(physician = ifelse(physician == "Охотин Артемий", 
                            "Артемий Охотин", physician)) %>%
  mutate(physician = ifelse(grepl("Мавлютов", record) & physician == "none",
                            'Константин Мавлютов', physician)) %>%
  mutate(physician = paste(substr(word(physician, 1), 1, 1), substr(word(physician, 2), 1, 1)))


# correcting propofol doses (inaccurately entered like mg, ml and not specified)
# we use 10 mg/ml solution and usually dose is from 2 to 40 ml (20-300 mg)
# 

df <- df %>%
  mutate(sedation_drug = sub('пропо.*', 'пропофол ', sedation)) %>%
  mutate(sedation_dose = case_when(
    grepl('[^0-9]+10[^0-9]+', sedation) ~ '100',
    grepl('[^0-9]*([0-9]+[05]) *мг.*', sedation) ~
      sub('[^0-9]*([0-9]+[05]) *мг.*', '\\1', sedation),
    grepl('.* ([0-9]+[\\,\\.][05])[^0-9]*', sedation) ~
      sub('.* ([0-9]+)[\\,\\.]([05])[^0-9]*', '\\1\\2', sedation),
    grepl('.* ([0-9]+0)[^0-9]*', sedation) ~ 
      sub('.* ([0-9]+0)[^0-9]*', '\\1', sedation),
    grepl('.* ([0-9]+[1-9])[^0-9]*', sedation) ~ 
      sub('.* ([0-9]+[1-9])[^0-9]*', '\\10', sedation),
    grepl('.* ([1-9])[^0-9]*', sedation) ~ 
      sub('.* ([1-9])[^0-9]*', '\\10', sedation),
    grepl('.* ([0-9]+)[^0-9]*', sedation) ~
      sub('.* ([0-9]+)[^0-9]*', '\\1', sedation),
    TRUE ~ 'n/a')
    ) %>%
  mutate(sedation_dose = as.integer(sedation_dose))

df <- df %>% 
  mutate(
    outcome = as.integer(ifelse(is.na(outcome), 0, outcome)),
    TEE = as.integer(ifelse(is.na(TEE), 0, TEE)),
    patient_age = as.integer(patient_age),
    followup_arrhythmia = as.Date(followup_arrhythmia),
    followup_sinus = as.Date(followup_sinus),
    date = as.Date(date),
    weekday = wday(date)
  )

#### Anticoagulation

df <- df %>%
  ungroup() %>%
  rowwise() %>%
  mutate(
    ac_drug=case_when(
      grepl("warfarin", anticoagulation) ~ "warfarin",
      grepl("ксарелто", anticoagulation) ~ "NOAC",
      grepl("ксралето", anticoagulation) ~ "NOAC",
      grepl("xarelto", anticoagulation) ~ "NOAC",
      grepl("apixaban", anticoagulation) ~ "NOAC",
      grepl("pradaxa", anticoagulation) ~ "NOAC",
      anticoagulation==0 | anticoagulation=="" ~ "none",
      TRUE ~ "none"
    ),
    ac_chronic = ifelse(ac_drug =="none", 0, 1)
  )

df$anticoagulation <-  factor(df$anticoagulation, levels=c("warfarin", "NOAC", "none"),
                              labels=c("Warfarin", "NOAC", "None"))

### Shocks

df <- df %>%
  ungroup() %>%
  mutate(
    shocks = 1 + str_count(joules, ' '),
    joules = as.numeric(word(joules, -1))
)
    
    
################ Duration of AF


df <- df %>% mutate(
  duration_of_af = case_when(
    duration_of_af %in% c("1", "2") ~ "less than 48 hours",
    duration_of_af %in% c("3", "4", "5", "6", "7") ~ "less than a week",
    TRUE ~ duration_of_af
  )
)

df$duration_of_af <- factor(df$duration_of_af, levels=c("less than 48 hours",
                                                        "less than a week",
                                                        "more than a week",
                                                        "more than a month",
                                                        "unknown"))
################


df <- df %>%
  select(
    id, outcome, Drug, joules, shocks, sedation_dose, duration_of_af,
    arrhythmia, ac_drug, ac_chronic,
    settings, complications,
    followup_sinus, followup_arrhythmia, followup_rhythm,
    aad, physician, date, 
    patient_age, patient_sex, patient_id, TEE, record_id, 
    weekday
  )

## Epidose number assigned to every cardioversion

df <- df %>%
  group_by(patient_id) %>%
  arrange(date) %>%
  mutate(event_id = row_number())


## Writing record_id-s to file
# Comorbidities are generated by Echodata according to this list

write.csv(df$record_id, "/home/okhotin/Dropbox/echoview/working/list.csv")


############ COMORBIDITIES

cmb <- read.csv("/home/okhotin/Dropbox/R/masters/comorbidities.csv")

colnames(cmb) <- c('CHD', 'HF0', 'HF1', 'DM', 'HTN0', 'HTN1', 'CKD0', 'CKD1', 'CKD2', 
  'MI', 'STROKE0', 'STROKE1', 'MED', 'record_id')

cmb$CHD <- cmb$CHD + cmb$MI
cmb$HF <- cmb$HF1 + cmb$HF0
cmb$HTN <- cmb$HTN1 + cmb$HTN0
cmb$CKD <- cmb$CKD1 + cmb$CKD0 +cmb$CKD2
cmb$STROKE <- cmb$STROKE0 + cmb$STROKE1
cmb <- cmb %>%
  select(CHD, HF, DM, HTN, CKD, STROKE, MED, record_id) %>%
  mutate(
    CHD = as.integer(CHD>0),
    HF = as.integer(HF>0),
    DM = as.integer(DM>0),
    HTN = as.integer(HTN>0),
    CKD = as.integer(CKD>0),
    STROKE = as.integer(STROKE>0)
  ) 
  

cmb$cmbs <- cmb$CHD + cmb$HF + cmb$HTN + cmb$CKD + cmb$STROKE
fit <- lm(data=cmb, MED ~ cmbs)

# signigicant association b/w number of comorbidities (cmbs) and 
# medication index (MED)


#cmb %>% ggplot(aes(x=cmbs, group=cmbs, y=MED, fill=as.factor(cmbs))) +
#  geom_boxplot() +
#  labs(x='Number of comorbidities', y = 'Medication index')

df$record_id <- as.integer(df$record_id)

df <- left_join(df, cmb, by=c("record_id"))
df <- left_join(df, echo_single, by=c("patient_id"))

#### misc

df$date <- as.Date(df$date)
df$followup_arrhythmia <- as.Date(df$followup_arrhythmia)
df$followup_sinus <- as.Date(df$followup_sinus)

# joules -- number of shocks, maximum shock



################################# description

# id -- unique id of episode (cardioversion)
# outcome -- immedicate success of cardioversion
# Drug -- drugs used pericardioversion
# joules -- shicks delivered 
# sedation_dose -- dose of propofol
#  duration_of_af -- duration of af episode (no more than for 1-7, 
#                    unknown if not specified or unknown (better to differentiate)
# arrhythmia -- type of arrhythmia (AF or AFlutter),
# ac_chronic -- chronic anticoagulation, defined as for more than 4 weeks or
#                     from previous sinuscardioversion or TEE, 
# ac_drug -- drug used for anticoagulation (warfarin/noac)
# settings -- inpatient or outpatient, complicated or not,
# complications -- complications encounetered (text),
# followup_sinus -- latest sinus rhythm registered,
# followup_arrhythmia -- date of next episode of arrhythmia,
# followup_rhythm -- type of this episode (paroxysm, self-terminating paroxysm or chronic AF),
# aad -- antiarhythmic drug administered after cardioversion
# physician -- physician performed
# date -- date of episode,
# patient_age -- age of the patient at the moment of cardioversion
# patient_sex -- sex of the patient,
# patient_id -- unique identifier of the patient,
# TEE -- wheter TEE was performed before cardioversion,
# record_id -- unique identifier of the record (accessibole thru EHR),
# weekday -- weekday of the event,
# event_id -- number of event for the patient,
# CHD -- coronary heart disease (ИБС, инфаркт in any record before index episode, including)
# HF -- heart failure (ХСН, сердечная недостаточность),
# DM -- diabetes mellitus (сахарный диабет),
# HTN -- arterial hypertension (артериальная гиперт, гипертоническая болезнь),
# CKD -- kidney disease (ХПН, ХБП, почечная недостаточность),
# STROKE -- stroke (инсульт, ОНМК),
# MED -- medication index, mean nubmer of dosages specifiers (мг, мкг, ед) in
#         all previous records including index, where it is 1 or more,
#         to exclude procedures and examinations.
# cmbs -- number of comorbidities (sum of previous columns except MED),
# weight, height, BSA -- mean weight, height and BSA collected from all
#                 echocardiography examinations,
# edvi, ef, lvmi, lavi -- echocardiographic parameters, taken from the first 
#                         study, where it is encountered.
#           end-diastolic left ventricular volume, 
#           ejection fraction
#           left ventricular mass index,
#           lavi -- left atrial volume index


## Patient level data-set (event -- chronic atrial fibrillation)

df <- df %>%
  group_by(patient_id) %>%
  arrange(desc(date)) %>%
  mutate(event_reverse_id = row_number()) %>%
  ungroup()

caf <- df %>%
  rowwise() %>%
  mutate(
    event_date = max(na.omit(c(followup_arrhythmia, followup_sinus, date))),
    event_type =
      case_when(
        !is.na(followup_sinus) & followup_sinus == event_date ~ 0,
        !is.na(followup_arrhythmia) &  followup_arrhythmia == event_date ~ 
          ifelse(grepl("chronic", followup_rhythm), 1, 0),
        date == event_date & outcome == 0 ~ 1,
        TRUE ~ 0
        )
  )


#caf$event_date <- as.Date(d$event_date, origin = "1970-01-01")

caf <- caf %>%
  group_by(patient_id) %>%
  arrange(date) %>%
  mutate(
    event_time = last(event_date) - first(date),
    event_type = last(event_type)
  ) %>%
  ungroup() %>%
  filter(event_id==1)



## Procedure level data-set (event -- repeated procedure or chronic af)



dc <- df %>%
  rowwise() %>%
  mutate(
    event_date = case_when(
      (is.na(followup_sinus) & is.na(followup_arrhythmia)) ~ date,
      (!is.na(followup_sinus) & is.na(followup_arrhythmia)) ~ followup_sinus,
      (is.na(followup_sinus) & !is.na(followup_arrhythmia)) ~ followup_arrhythmia,
      TRUE ~ followup_arrhythmia
    ),
    event_time = event_date-date, 
    event_type = ifelse(
      is.na(followup_arrhythmia), 0, 1
      ),
    unstable = ifelse(grepl("unstable", settings), 1, 0),
    settings = ifelse(grepl("inpatient", settings), "inpatient", 
                      ifelse(grepl("outpatient", settings), "outpatient", "n/a")),
    
    
    ) %>%
  filter(patient_age<100)


################


################# Counts of events by calendar day

counts <- data.frame(date=as.Date(as.Date("2016-01-01"):as.Date("2022-11-30"), origin="1970-01-01"))
counts$dc <- 0

dc1 <- dc
for (date in counts$date){
  counts[counts$date==date,]$dc <- nrow(dc1[dc1$date==date,])
  
}
counts$wday <- factor(wday(counts$date))
counts$month <- factor(month(counts$date))
counts$year <- year(counts$date)
counts$week <-  factor(week(counts$date))
counts <- counts %>%
  mutate(
    summer = ifelse(month %in% c(1,2,3,4,5,9,10,11,12), "winter", "summer")
  )

counts$wday <- factor(counts$wday, 
                             levels=(c(2,3,4,5,6,7,1)),
                             labels=c('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'))

counts48 <- data.frame(date=as.Date(as.Date("2016-01-01"):as.Date("2022-11-30"), origin="1970-01-01"))
counts48$dc <- 0

dc1 <- dc[dc$duration_of_af=='less than 48 hours',]
for (date in counts48$date){
  counts48[counts48$date==date,]$dc <- nrow(dc1[dc1$date==date,])
  
}
counts48$wday <- factor(wday(counts48$date))
counts48$month <- factor(month(counts48$date))
counts48$year <- year(counts48$date)
counts48$week <-  factor(week(counts48$date))
counts48 <- counts48 %>%
  mutate(
    summer = ifelse(month %in% c(1,2,3,4,5,9,10,11,12), "winter", "summer")
  )
counts48$wday <- factor(counts48$wday, 
                      levels=(c(2,3,4,5,6,7,1)),
                      labels=c('Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'))



########## export


### 

write.csv(counts, "~/Dropbox/R/masters/counts.csv")
write.csv(counts48, "~/Dropbox/R/masters/counts48.csv")
write.csv(dc, "~/Dropbox/R/masters/dc.csv")
write.csv(caf, "~/Dropbox/R/masters/caf.csv")

